---
abstract: 'A 2d web game engine, for turn based games written in Perl'
author:
  - 'David Farrell <sillymoos@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: March
requires:
  Math::Shape::Circle: '0'
  feature: '0'
  perl: '5.020'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/sillymoose/March
  repository: https://github.com/sillymoose/March.git
version: '0.01'
