=pod

=encoding UTF-8

=head1 NAME

March - This is an experiment - a 2d game engine, for turn based games written in Perl using the Entity-Component pattern.

=head1 VERSION

version 0.01

=head1 AUTHOR

David Farrell <dfarrell@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2015 by David Farrell.

This is free software, licensed under:

  The (two-clause) FreeBSD License

=cut
